name: Run on every PR

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'extras/**'
      - '**.md'
      - '**.adoc'

jobs:
  # TODO: Add unit test as well here
  tests:
    name: Kadalu Storage Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Binnacle
        run: |
          curl -L https://github.com/kadalu/binnacle/releases/latest/download/binnacle -o binnacle
          chmod +x ./binnacle
          sudo mv ./binnacle /usr/local/bin/binnacle
          binnacle --version
      - name: Build Storage node container
        run: |
          cd tests && ./build-container.sh
      - name: Setup Test environment
        run: sudo binnacle -v tests/setup.t
      - name: Build and Install Storage manager to nodes/containers
        run: sudo VERSION="${{ github.ref_name }}" binnacle -v tests/install.t
      - name: Run all Tests - Amd64
        run: sudo ARCH=amd binnacle -v tests/all
      - name: Run all Tests - Arm64
        run: sudo ARCH=arm binnacle -v tests/all
