name: After merging PR

on:
  push:
    branches:
      - main
      - build_test

  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  devel-tag-push:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Install binnacle
      run: |
        curl -fsSL https://github.com/kadalu/binnacle/releases/latest/download/install.sh | sudo bash -x
    - name: Run Binnacle based packages generator
      run: |
        PACKAGING_GPG_SIGNING_KEY="${{ secrets.PACKAGING_GPG_SIGNING_KEY }}" binnacle -v ubuntu.22.04.t
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
